#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Math-Utils
Version  : 1.14
Release  : 26
URL      : https://cpan.metacpan.org/authors/id/J/JG/JGAMBLE/Math-Utils-1.14.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/J/JG/JGAMBLE/Math-Utils-1.14.tar.gz
Summary  : 'Useful mathematical functions not in Perl'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-Math-Utils-license = %{version}-%{release}
Requires: perl-Math-Utils-perl = %{version}-%{release}
BuildRequires : buildreq-cpan

%description
# Math-Utils
## Version 1.14
Contains implementations of commonly used mathematical functions
and operations that are not part of standard Perl.

%package dev
Summary: dev components for the perl-Math-Utils package.
Group: Development
Provides: perl-Math-Utils-devel = %{version}-%{release}
Requires: perl-Math-Utils = %{version}-%{release}

%description dev
dev components for the perl-Math-Utils package.


%package license
Summary: license components for the perl-Math-Utils package.
Group: Default

%description license
license components for the perl-Math-Utils package.


%package perl
Summary: perl components for the perl-Math-Utils package.
Group: Default
Requires: perl-Math-Utils = %{version}-%{release}

%description perl
perl components for the perl-Math-Utils package.


%prep
%setup -q -n Math-Utils-1.14
cd %{_builddir}/Math-Utils-1.14

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-Math-Utils
cp %{_builddir}/Math-Utils-1.14/LICENSE %{buildroot}/usr/share/package-licenses/perl-Math-Utils/7a5c834004a31487e2bc7ec3c33259bded907d1d
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Math::Utils.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-Math-Utils/7a5c834004a31487e2bc7ec3c33259bded907d1d

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
